version: '3'


# Network
networks: 
  casocavallo_network:
    ipam:
      config: 
        - subnet: 1.0.0.0/24 


# Services
services: 

  # Casocavallo random generator
  casocavallo_random_generator:
    build: './CasoCavallo/RandomGenerator'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.11'
    volumes: 
      - './CasoCavallo/RandomGenerator:/app/casocavallo/random_generator'
    command: ['python', 'Generator.py']

  # Redis server
  redis:
    build: './Redis'
    ports: 
      - '6379:6379'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.10'   
    command: [ 'redis-server', '/usr/local/etc/redis/redis.conf' ]

  # Cummare P2P layer - Server
  cummare_server:
    build: './Cummare'
    volumes: 
      - './Cummare:/app/cummare'
    stdin_open: true  # docker run -i
    tty: true
    ports:
      - 50052:50052
      - 50053:50053
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.12'
    command: [ 'npm', 'run', 'server' ]

  # Cummare P2P layer - Updater
  cummare_updater:
    build: './Cummare'
    volumes: 
      - './Cummare:/app/cummare'
    stdin_open: true  # docker run -i
    tty: true
    ports:
      - 50052:50052
      - 50053:50053
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.13'
    command: [ 'npm', 'run', 'updater' ]




  # **************** EXPERIMENTAL SERRVICES USING LIBP2P **************** :
  # Experimental P2P Layer - server
  casocavallo_experimental_p2p_layer_server:
    build: './CasoCavallo/EXPERIMENTAL_P2PLayer'
    volumes: 
      - './CasoCavallo/EXPERIMENTAL_P2PLayer:/app/casocavallo/p2p_layer'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.13'
    command: [ 'npm', 'run', 'server' ]

  # Experimental P2P Layer - client
  casocavallo_experimental_p2p_layer_client:
    build: './CasoCavallo/EXPERIMENTAL_P2PLayer'
    volumes: 
      - './CasoCavallo/EXPERIMENTAL_P2PLayer:/app/casocavallo/p2p_layer'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.14'
    command: [ 'npm', 'run', 'client' ]


