version: '3'


# Network
networks: 
  casocavallo_network:
    ipam:
      config:
        - subnet: 1.0.0.0/24 


# Services
services: 

  # Casocavallo Random Generator
  casocavallo:
    build: './CasoCavallo'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.3'
    volumes: 
      - './CasoCavallo:/app/casocavallo/random_generator'
      - './Configurations:/app/casocavallo/Configurations'
    command: ['python', 'main.py']

  # Redis server
  redis:
    build: './Redis'
    expose: 
      - 6379
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.2'   
    command: [ 'redis-server', '/usr/local/etc/redis/redis.conf' ]


  # Cummare P2P layer
  cummare:
    build: './Cummare'
    volumes: 
      - './Cummare:/app/cummare/p2p-pubsub-protocol'
      - './Configurations:/app/cummare/Configurations'
    stdin_open: true  # docker run -i
    tty: true
    ports:
      - 50052:50052
      - 50053:50053
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.11'
    command: [ 'npm', 'run', 'server' ]

