version: '3'


# Network
networks: 
  casocavallo_network:
    ipam:
      config:
        - subnet: 1.0.0.0/24 


# Services
services: 

  # Casocavallo Random Generator
  casocavallo_random_generator:
    build: './CasoCavallo/RandomGenerator'
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.3'
    volumes: 
      - './CasoCavallo/RandomGenerator:/app/casocavallo/random_generator'
    command: ['sh', 'start.sh']

  # Redis server of Casocavallo
  casocavallo_redis:
    build: './CasoCavallo/Redis'
    expose: 
      - 6379
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.2'   
    command: [ 'redis-server', '/usr/local/etc/redis/redis.conf' ]


  # Cummare P2P layer - Server
  cummare_server:
    build: './Cummare'
    volumes: 
      - './Cummare:/app/cummare'
    stdin_open: true  # docker run -i
    tty: true
    ports:
      - 50052:50052
      - 50053:50053
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.11'
    command: [ 'npm', 'run', 'server' ]

  # Redis server of Cummare
  cummare_redis:
    build: './Cummare/Redis'
    expose: 
      - 6379
    stdin_open: true  # docker run -i
    tty: true
    networks: 
      casocavallo_network:
        ipv4_address: '1.0.0.10'   
    command: [ 'redis-server', '/usr/local/etc/redis/redis.conf' ]
